### ISSUE TITLE
Hatalı Kod

### ISSUE THREAD

**Issue by cosane** [bozburak/Simple_Console_Apps_In_Python#1]
x sayısına kullanıcı hangi başlangıç değerini verirse versin fibonacci serisine 1'den başlanıyor. Normalde **x**e **3**, **n**ye **7** değerini verdiğimizde fibonacci serisinin 3,4,5,6,7 nolu sayılarını yazdırması gerekmez miydi? Bildiğim kadarıyla Fibonacci serisi 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89 diye devam ediyor. Bu durumda **a=0** ve **b=1** ile başlayıp devam etmek gerekir. a sayısı **birinci**, b sayısı **ikinci** elemandır ve ilk hesaplamada bulunan c sayısı ise **üçüncü** elamandır. Bundan sonraki her hesaplamada da  nasıl ki ilk hesaplamada **2'den bir fazlası**na ulaşıldıysa bu şekilde her seferinde sonraki elemana ulaşılacaktır. Bu durumda biz ilk hesaplama ile beşinci hesaplama arasını ekrana yazdırmalıyız ki 3-7 arasını yazdırmış olalım. Yanılıyor muyum?

**Comment by bozburak** [comment]
Düzeltildi.
Belirli bir döngü içerisinde fibonacci sayılarını listeledim.
