### ISSUE TITLE
"a" zaten integer

### ISSUE THREAD

**Issue by cosane** [bozburak/Simple_Console_Apps_In_Python#2]
a zaten bir integer, onu int ile kullanmak gereksiz olmuş. x için ise, daha x'i oluştururken inputu int parantezine alarak oluştursan programın kalanında int'siz kullansan daha derli toplu olur.

**Comment by bozburak** [comment]
Düzelttim (-_-)
Çok teşekkürler hocam bu çok iyi oldu benim için.
